# Based on
# https://github.com/fedarko/strainFlye/blob/main/.github/workflows/main.yml,
# which was in turn "[based] roughly on the main.yml and standalone.yml 
# workflows in
# https://github.com/biocore/empress/blob/master/.github/workflows/,
# and on https://docs.github.com/en/actions/quickstart". It's copy-and-paste
# all the way down baybee
name: wotplot CI
on: [push, pull_request]
jobs:
  build:
    # Pinning OS to Ubuntu 20.04, since "ubuntu-latest" (22.04, as of writing)
    # dropped support for Python 3.6. Ideally we'd conditionally set the OS
    # based on the Python version but I can't figure out how to do that :|
    # shouldn't make a big difference for now, esp. since we're not doing any
    # crazy systems-level stuff here
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:

      # Updating from v2 to v3 to match, as of writing,
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
      - name: Check out code
        uses: actions/checkout@v3

      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sanity check echo python version
        run: python --version

      - name: Sanity check echo python location
        run: which python

      - name: Sanity check echo pip version
        run: pip --version

      - name: Sanity check echo pip location
        run: which pip

      - name: Install wotplot and pip dependencies
        run: pip install -e .[dev]

      - name: Lint and stylecheck
        run: make stylecheck

      - name: Run tests
        run: make test

      - name: Upload code coverage information to Codecov
        uses: codecov/codecov-action@v2
