# Based on
# https://github.com/fedarko/strainFlye/blob/main/.github/workflows/main.yml,
# which was in turn "[based] roughly on the main.yml and standalone.yml 
# workflows in
# https://github.com/biocore/empress/blob/master/.github/workflows/,
# and on https://docs.github.com/en/actions/quickstart". It's copy-and-paste
# all the way down baybee
name: wotplot CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:

      # Updating from v2 to v3 to match, as of writing,
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
      - name: Check out code
        uses: actions/checkout@v3

      # Set up a conda env using mamba (which is much faster than conda).
      # We can use "create-args" to adjust the python version; based on
      # https://github.com/mamba-org/setup-micromamba/issues/51#issue-1688507017
      - name: Install conda dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: python=${{ matrix.python-version }}
          init-shell: bash

      - name: Sanity check echo python version
        run: python --version
        shell: bash

      - name: Sanity check echo python location
        run: which python
        shell: bash

      - name: Sanity check echo pip version
        run: pip --version
        shell: bash

      - name: Sanity check echo pip location
        run: which pip
        shell: bash

      - name: Install wotplot (and pip dependencies)
        run: pip install -e .[dev,viz]
        shell: bash

      - name: Lint and stylecheck
        run: make stylecheck
        shell: bash

      - name: Run tests
        run: make test
        shell: bash

      - name: Upload code coverage information to Codecov
        uses: codecov/codecov-action@v2
